package golem:component;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface api {
  start: func() -> string;
}

world cpu100 {
  export api;
}
